package db.migration;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Statement;
import java.util.List;
import java.util.Locale;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

/**
 * Creates the schema that was previously owned by Hibernate and the admin
 * bootstrap runner. The identity and large-text definitions are database
 * specific, while table and column names remain shared with the JPA model.
 */
public class V1__CreateInitialSchema extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        String databaseProduct = databaseProduct(context.getConnection());
        for (String statementSql : schemaStatements(databaseProduct)) {
            try (Statement statement = context.getConnection().createStatement()) {
                statement.execute(statementSql);
            }
        }
    }

    private String databaseProduct(Connection connection) throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        return metadata.getDatabaseProductName().toLowerCase(Locale.ROOT);
    }

    private List<String> schemaStatements(String databaseProduct) {
        String pipelineIdDefinition;
        String definitionTextType;
        if (databaseProduct.contains("sqlite")) {
            pipelineIdDefinition = "integer primary key autoincrement";
            definitionTextType = "clob";
        } else if (databaseProduct.contains("mysql")) {
            pipelineIdDefinition = "bigint not null auto_increment primary key";
            definitionTextType = "longtext";
        } else if (databaseProduct.contains("h2")) {
            pipelineIdDefinition = "bigint generated by default as identity primary key";
            definitionTextType = "clob";
        } else {
            throw new IllegalStateException("Unsupported database for StreamCraft schema migration: " + databaseProduct);
        }

        return List.of(
                """
                create table users (
                    username varchar(50) not null primary key,
                    password varchar(500) not null,
                    enabled boolean not null
                )
                """,
                """
                create table authorities (
                    username varchar(50) not null,
                    authority varchar(50) not null,
                    constraint fk_authorities_users foreign key (username) references users(username),
                    constraint uk_authorities unique (username, authority)
                )
                """,
                """
                create table pipelines (
                    id %s,
                    created_at timestamp not null,
                    definition_json %s not null,
                    description varchar(255),
                    last_job_id varchar(255),
                    last_run_message varchar(255),
                    last_run_status varchar(255) check (last_run_status in ('RUNNING','FAILED','STOPPED')),
                    last_submitted_at timestamp,
                    name varchar(255) not null unique,
                    updated_at timestamp not null
                )
                """.formatted(pipelineIdDefinition, definitionTextType),
                """
                create table flink_runtime_target (
                    id bigint not null,
                    available_slots integer,
                    created_at timestamp,
                    flink_version varchar(255),
                    job_manager_url varchar(255),
                    last_validated_at timestamp,
                    status varchar(255) not null check (status in ('CONNECTED','UNREACHABLE','UNKNOWN')),
                    status_message varchar(255),
                    task_manager_count integer,
                    total_slots integer,
                    type varchar(255) not null check (type in ('FLINK_STANDALONE')),
                    updated_at timestamp,
                    primary key (id)
                )
                """);
    }
}
